setup code coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,14 +52,14 @@ jobs:
         with:
           encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
       - name: Run Unit Tests
-        run: ./gradlew test
-#      - name: Codecov
-#        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
-#        with:
-#          files: ./build/reports/kover/report.xml
-#          token: ${{ secrets.CODECOV_TOKEN  }}
-#      - name: Publish Test Report
-#        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
-#        if: success() || failure() # always run even if the previous step fails
-#        with:
-#          report_paths: '**/build/reports/kover/report.xml'
+        run: ./gradlew koverXmlReport --no-build-cache
+      - name: Codecov
+        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
+        with:
+          files: ./build/reports/kover/report.xml
+          token: ${{ secrets.CODECOV_TOKEN  }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/app/build/reports/kover/report.xml'
